name: Deploy API Server to Heroku
on:
  push:
    branches:
      - 'master'
    paths:
      - 'api/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Deploy app to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'jamstack-ecommerce-example-api'
          heroku_email: 'georg.wittberger@gmail.com'
          appdir: 'api'
        env:
          HD_YARN_PRODUCTION: 'true'
